name: Test Action

on:
  push:
    branches:
      - main   # or whichever branch you want

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 23f2003735@ds.study.iitm.ac.in
        run: echo "Hello, world!"
